INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (1, 1, 'Verwarmingslichaam duidelijk waarneembaar', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (2, 1, 'Afvoer van de ketel is waarneembaar', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (3, 1, 'Schoorsteen was in werking', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (4, 1, 'Leidingen vn de verwarming waarneembaar', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (5, 1, 'Afvoer decentrale verwarming waarneembaar', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (7, 3, 'De ramen zijn vernieuwd', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (8, 3, 'De ramen bevatten rolluiken en geven extra bescherming', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (9, 3, 'De afwerking van de rolluikkasten op vlak van isolatie en luchtdichtheid', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (10, 3, 'De afwerking van de dagkanten van de ramen', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (11, 3, 'De luchttoevoerroosters zijn waarneembaar op de foto', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (12, 3, 'Raam stond open tijdens onze gevelscan', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (13, 3, 'Oude ramen hebben sterke infiltraties (geen of versleten dichtingen)', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (14, 4, 'Het dakraam is hedendaags', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (15, 4, 'Het dakraam bestaat uit een metalen frame met enkele beglazing', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (16, 4, 'Één bepaalde ruimte verwarmd', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (17, 5, 'De afwerking van de dagkanten van de deur', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (18, 5, 'De deur bevat glas met een sterke geleiding', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (19, 5, 'De deur bevat een paneel met sterke geleiding', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (20, 5, 'De deur(en) zijn vernieuwd', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (21, 5, 'De deur(en) zijn verouderd', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (22, 5, 'Infiltraties via de deur', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (23, 6, 'Sterke infiltraties via de poort', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (24, 6, 'De poort sluit niet zo goed', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (25, 6, 'De afwerking van de dagkanten ontbreekt', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (26, 6, 'De poort vertoond een sterke geleiding', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (27, 6, 'Er is geen afsluiting t.o.v. de spouw, groot warmteverlies', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (28, 6, 'De poort is geïsoleerd', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (29, 6, 'De poort is niet geïsoleerd', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (30, 6, 'De poort is vernieuwd', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (31, 7, 'Brieven aanwezig in de deur', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (32, 7, 'Brievenbus op de muur gemonteerd', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (33, 7, 'Grote infiltraties', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (34, 7, 'Brievenbus ingewerkt in de muur', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (92, 8, 'De muren hebben geen uniforme kleur, de muur is niet of onvoldoende geïsoleerd', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (93, 8, 'De muren hebben een uniforme kleur en zijn geïsoleerd', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (94, 8, 'De muren kleuren uniform, de spouw werd na geïsoleerd d.m.v. spouwvulling', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (95, 8, 'De muren beschikken over een basisisolatie', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (96, 8, 'De kleur van de muren kan variëren in functie van stooktemperatuur', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (97, 8, 'De kleur van de muren kan variëren als de aanpalende ruimte is verwarmd of niet', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (98, 8, 'Men kan warmtestromen vaststellen in de spouw', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (99, 8, 'De muur is begroeid met beplantingen', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (100, 8, 'De muur is op bepaalde plaatsen vochtig', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (101, 8, 'Er is een afkoeling van de muur door de wind', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (102, 8, 'Binnenhoek vertonen een grotere warmteuitstraling', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (103, 9, 'Het dak heeft een uniforme kleur, dit impliceert wellicht een vorm van isolatie, hoe kouder het dak, hoe donkerder de kleur, hoe groter de isolatiewaarde', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (104, 9, 'De kleur van het dak dient men te interpreteren in functie van de onderliggende temperatuur', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (105, 9, 'De kleur van het dak dient men te interpreteren in functie van de onderliggende temperatuur', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (106, 9, 'Één dakdeel is beter geïsoleerd dan het andere dakdeel', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (107, 9, 'De dakisolatie bevat niet conformiteiten (vb ontbrekende stukken isolatie', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (108, 9, 'De aansluiting van de dakramen aan de dakisolatie', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (109, 9, 'Het dak heeft geen uniforme kleur, het dak is waarschijnlijk niet geïsoleerd of de isolatie is slecht geplaatst', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (110, 9, 'Warmteuitstraling (reflectie) van naast gelegen muur op het dakdeel', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (111, 9, 'Reflecties van metalen delen zoals lood, zinkwerk, koper, …', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (112, 10, 'Geen hernieuwbare energie vastgesteld, investeer en geniet van de gratis zonne energie, uw dak leunt zich tot zonnepanelen en zonneboiler', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (113, 10, 'Geen hernieuwbare energie vastgesteld, maar is wel aanwezig op een andere dakdeel', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (114, 10, 'Zonnepanelen zijn waarneembaar op het dak', 1);
INSERT INTO thermoloket.eigenschappen (id, categorie_id, beschrijving, `default`) VALUES (115, 10, 'Zonneboiler is waarneembaar op het dak', 1);