insert into thermoloket.bouwjaren (id, bottom, top) values (1, '<1900', 1950);
insert into thermoloket.bouwjaren (id, bottom, top) values (2, 1950, 1970);
insert into thermoloket.bouwjaren (id, bottom, top) values (3, 1970, 1980);
insert into thermoloket.bouwjaren (id, bottom, top) values (4, 1980, 2000);
insert into thermoloket.bouwjaren (id, bottom, top) values (5, 2000, 2006);
insert into thermoloket.bouwjaren (id, bottom, top) values (6, 2006, 2008);
insert into thermoloket.bouwjaren (id, bottom, top) values (7, 2008, 2011);
insert into thermoloket.bouwjaren (id, bottom, top) values (8, 2011, '2020>');

insert into thermoloket.categorieen (id, input_type_id, titel, gewicht, geactiveerd, hoofdbalk) values (1, 1, 'Gevel', 0, 1, 1);
insert into thermoloket.categorieen (id, input_type_id, titel, gewicht, geactiveerd, hoofdbalk) values (2, 3, 'Openingen', 1, 1, 1);
insert into thermoloket.categorieen (id, input_type_id, titel, gewicht, geactiveerd, hoofdbalk) values (3, 2, 'Ramen', 0, 1, 0);
insert into thermoloket.categorieen (id, input_type_id, titel, gewicht, geactiveerd, hoofdbalk) values (4, 2, 'Dakramen', 1, 1, 0);
insert into thermoloket.categorieen (id, input_type_id, titel, gewicht, geactiveerd, hoofdbalk) values (5, 2, 'Deuren', 2, 1, 0);
insert into thermoloket.categorieen (id, input_type_id, titel, gewicht, geactiveerd, hoofdbalk) values (6, 2, 'Poorten', 3, 1, 0);
insert into thermoloket.categorieen (id, input_type_id, titel, gewicht, geactiveerd, hoofdbalk) values (7, 2, 'Brievenbus', 4, 1, 0);
insert into thermoloket.categorieen (id, input_type_id, titel, gewicht, geactiveerd, hoofdbalk) values (8, 2, 'Muren', 2, 1, 1);
insert into thermoloket.categorieen (id, input_type_id, titel, gewicht, geactiveerd, hoofdbalk) values (9, 2, 'Dak', 3, 1, 1);
insert into thermoloket.categorieen (id, input_type_id, titel, gewicht, geactiveerd, hoofdbalk) values (10, 2, 'Energiebronnen', 4, 1, 1);
insert into thermoloket.categorieen (id, input_type_id, titel, gewicht, geactiveerd, hoofdbalk) values (11, 2, 'Verwarming', 0, 1, 0);

insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (1, 1, 'Verwarmingslichaam duidelijk waarneembaar', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (2, 1, 'Afvoer van de ketel is waarneembaar', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (3, 1, 'Schoorsteen was in werking', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (4, 1, 'Leidingen vn de verwarming waarneembaar', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (5, 1, 'Afvoer decentrale verwarming waarneembaar', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (7, 3, 'De ramen zijn vernieuwd', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (8, 3, 'De ramen bevatten rolluiken en geven extra bescherming', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (9, 3, 'De afwerking van de rolluikkasten op vlak van isolatie en luchtdichtheid', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (10, 3, 'De afwerking van de dagkanten van de ramen', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (11, 3, 'De luchttoevoerroosters zijn waarneembaar op de foto', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (12, 3, 'Raam stond open tijdens onze gevelscan', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (13, 3, 'Oude ramen hebben sterke infiltraties (geen of versleten dichtingen)', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (14, 4, 'Het dakraam is hedendaags', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (15, 4, 'Het dakraam bestaat uit een metalen frame met enkele beglazing', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (16, 4, 'Één bepaalde ruimte verwarmd', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (17, 5, 'De afwerking van de dagkanten van de deur', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (18, 5, 'De deur bevat glas met een sterke geleiding', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (19, 5, 'De deur bevat een paneel met sterke geleiding', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (20, 5, 'De deur(en) zijn vernieuwd', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (21, 5, 'De deur(en) zijn verouderd', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (22, 5, 'Infiltraties via de deur', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (23, 6, 'Sterke infiltraties via de poort', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (24, 6, 'De poort sluit niet zo goed', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (25, 6, 'De afwerking van de dagkanten ontbreekt', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (26, 6, 'De poort vertoond een sterke geleiding', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (27, 6, 'Er is geen afsluiting t.o.v. de spouw, groot warmteverlies', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (28, 6, 'De poort is geïsoleerd', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (29, 6, 'De poort is niet geïsoleerd', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (30, 6, 'De poort is vernieuwd', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (31, 7, 'Brieven aanwezig in de deur', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (32, 7, 'Brievenbus op de muur gemonteerd', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (33, 7, 'Grote infiltraties', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (34, 7, 'Brievenbus ingewerkt in de muur', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (92, 8, 'De muren hebben geen uniforme kleur, de muur is niet of onvoldoende geïsoleerd', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (93, 8, 'De muren hebben een uniforme kleur en zijn geïsoleerd', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (94, 8, 'De muren kleuren uniform, de spouw werd na geïsoleerd d.m.v. spouwvulling', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (95, 8, 'De muren beschikken over een basisisolatie', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (96, 8, 'De kleur van de muren kan variëren in functie van stooktemperatuur', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (97, 8, 'De kleur van de muren kan variëren als de aanpalende ruimte is verwarmd of niet', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (98, 8, 'Men kan warmtestromen vaststellen in de spouw', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (99, 8, 'De muur is begroeid met beplantingen', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (100, 8, 'De muur is op bepaalde plaatsen vochtig', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (101, 8, 'Er is een afkoeling van de muur door de wind', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (102, 8, 'Binnenhoek vertonen een grotere warmteuitstraling', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (103, 9, 'Het dak heeft een uniforme kleur, dit impliceert wellicht een vorm van isolatie, hoe kouder het dak, hoe donkerder de kleur, hoe groter de isolatiewaarde', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (104, 9, 'De kleur van het dak dient men te interpreteren in functie van de onderliggende temperatuur', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (105, 9, 'De kleur van het dak dient men te interpreteren in functie van de onderliggende temperatuur', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (106, 9, 'Één dakdeel is beter geïsoleerd dan het andere dakdeel', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (107, 9, 'De dakisolatie bevat niet conformiteiten (vb ontbrekende stukken isolatie', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (108, 9, 'De aansluiting van de dakramen aan de dakisolatie', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (109, 9, 'Het dak heeft geen uniforme kleur, het dak is waarschijnlijk niet geïsoleerd of de isolatie is slecht geplaatst', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (110, 9, 'Warmteuitstraling (reflectie) van naast gelegen muur op het dakdeel', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (111, 9, 'Reflecties van metalen delen zoals lood, zinkwerk, koper, …', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (112, 10, 'Geen hernieuwbare energie vastgesteld, investeer en geniet van de gratis zonne energie, uw dak leunt zich tot zonnepanelen en zonneboiler', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (113, 10, 'Geen hernieuwbare energie vastgesteld, maar is wel aanwezig op een andere dakdeel', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (114, 10, 'Zonnepanelen zijn waarneembaar op het dak', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (115, 10, 'Zonneboiler is waarneembaar op het dak', 1);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (116, 11, 'Gelijkvloers is verwarmd', 0);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (117, 11, 'Gelijkvloers is niet verwarmd', 0);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (118, 11, '1ste verdiep is verwarmd', 0);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (119, 11, '1ste verdiep is indirect verwarmd', 0);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (120, 11, 'Ruimte onder hellend dak is verwarmd', 0);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (121, 11, 'Ruimte onder hellend dak is niet verwarmd', 0);
insert into thermoloket.eigenschappen (id, categorie_id, beschrijving, default) values (122, 11, 'Slechts bepaalde ruimtes worden verwarmd', 0);

insert into thermoloket.gebruikers (id, naam, wachtwoord, laatste_login, email, ingeschakeld) values (1, 'jesse2', '$2y$10$scffjhhI3zjgyOOmkGZGK.dA1QIuRcRJ.7b/gTe8jPIGhql88pZlq', null, 'jessevdkk', 0);
insert into thermoloket.gebruikers (id, naam, wachtwoord, laatste_login, email, ingeschakeld) values (2, 'Vincentje2', '$2y$10$48SEPumuhgC8BG7PdSIyK.ZQH8USqD5XDnEMCbhUARX2Be1JORUOy', null, 'jessevincent2', 0);
insert into thermoloket.gebruikers (id, naam, wachtwoord, laatste_login, email, ingeschakeld) values (3, 'enabled', '$2y$10$T51wvsYmB.R3Vr0tVHa8cu4PzVW0JxxPbCcw9xBMpd9g939zedpc.', null, 'enabled', 1);
insert into thermoloket.gebruikers (id, naam, wachtwoord, laatste_login, email, ingeschakeld) values (4, 'leonard', '$2y$10$.y9veIu2Urisi4ea2CBLQeaXb9rDCkBTAnavKHWi7ZLY5LjRNf7um', null, 'leonard', 1);
insert into thermoloket.gebruikers (id, naam, wachtwoord, laatste_login, email, ingeschakeld) values (5, 'user', '$2y$10$IGmr8KQ5h4QMRCVNOtyhK.coOX5lawGZ4nqVOwzqIrG0gLwkD4aSG', null, 'user', 1);
insert into thermoloket.gebruikers (id, naam, wachtwoord, laatste_login, email, ingeschakeld) values (6, 'lol', '$2y$10$QHhA7i8mL3XwCXF8ZAS/sOUAGqr.gFkF1/16vRJ7W16GSdezFuari', null, 'lol', 1);
insert into thermoloket.gebruikers (id, naam, wachtwoord, laatste_login, email, ingeschakeld) values (7, 'admin', '$2y$10$6d6rG9XZF7Zj79acZA3c1eTHmR3YrGp0heoOqhqYZ7BhtczFzLHQK', null, 'admin', 1);


insert into thermoloket.input_types (id, titel) values (1, 'checkbox');
insert into thermoloket.input_types (id, titel) values (2, 'selectie');
insert into thermoloket.input_types (id, titel) values (3, 'subcategorie');

insert into thermoloket.is_subcategorie_van (id, categorie_id, subcategorie_id) values (1, 2, 3);
insert into thermoloket.is_subcategorie_van (id, categorie_id, subcategorie_id) values (2, 2, 4);
insert into thermoloket.is_subcategorie_van (id, categorie_id, subcategorie_id) values (3, 2, 5);
insert into thermoloket.is_subcategorie_van (id, categorie_id, subcategorie_id) values (4, 2, 6);
insert into thermoloket.is_subcategorie_van (id, categorie_id, subcategorie_id) values (5, 2, 7);

insert into thermoloket.waarneming_types (id, titel, kleur) values (1, 'schitterend', 'green');
insert into thermoloket.waarneming_types (id, titel, kleur) values (2, 'mooi resultaat', 'light-green');
insert into thermoloket.waarneming_types (id, titel, kleur) values (3, 'goed op weg', 'yellow');
insert into thermoloket.waarneming_types (id, titel, kleur) values (4, 'aanpakken', 'orange');
insert into thermoloket.waarneming_types (id, titel, kleur) values (5, 'dringend aanpakken', 'red');
insert into thermoloket.waarneming_types (id, titel, kleur) values (6, 'niet van toepassing', 'white');
